version: 2
jobs:
  test-compile:
    docker:
      - image: qtoggle/espqtoggle-builder
    steps:
      - checkout
      - run: |
          export SRC_DIR="${CIRCLE_WORKING_DIRECTORY}"
          export EB_CONF_FILES=${CI_PROJECT_DIR}/test/configurations/*.conf
          /opt/builder.sh

  run-automated-tests:
    docker:
      - image: qtoggle/espqtoggle-builder
    steps:
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test-compile
      - run-automated-tests:
          context: qtoggle-global
          type: approval
          filters:
            branches:
              only: dev
